apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app01
  namespace: demoapp01
spec:
  rules:
  - host: "app01.YOUR_TEST_VM_FOR_LB_IP.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app01
            port:
              number: 8080
